##################################################################################################
# Demo MOCK service
##################################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-mock
  namespace: test
  labels:
    app: demo
    version: 1-mock
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
      version: 1-mock
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo
        version: 1-mock
    spec:
#      serviceAccountName: demo-sa
      containers:
        - image: docker-registry:port/org/demo-service:1.0-MOCK
          imagePullPolicy: IfNotPresent
          name: demo
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 150
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /actuator
              port: 8080
          readinessProbe:
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 2000m
              memory: 1000Mi
          volumeMounts:
            - name: config
              mountPath: /usr/share/service/config
      imagePullSecrets:
        - name: docker-secret
      volumes:
        - name: config
          configMap:
            name: demo-config
      nodeSelector:
        role: worker